spring:
  application:
    name: bbx-adhoc-batch
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

---
spring:
  config:
    activate:
      on-cloud-platform: KUBERNETES
    import: "configserver:"
  cloud:
    config:
      uri: http://spring-cloud-config-server

management:
  metrics:
    export:
      prometheus:
        pushgateway:
          enabled: true
          baseUrl: "http://prometheus-pushgateway:9091"

